---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine

inputs:
- name: some-important-input
outputs:
- name: output

run:
  path: cp . ../output && ls -l ../output
